Repository TrixiEther/DashchanFork, pull requests merged in 2023-07, with the labels that each got.

#91 TrixiEther | Release 1.6.1
  build.gradle
  metadata/en-US/changelogs/1052.txt
  metadata/ru/changelogs/1052.txt
  metadata/versions.json
Labels: bug, enhancement

#92 3.1.4 experimental 1.6.1 prerelease
  README.md
  build.gradle
  lang/values-ru/strings.xml
  lang/values/strings.xml
  metadata/en-US/changelogs/1052.txt
  metadata/ru/changelogs/1052.txt
  metadata/versions.json
  res/layout/activity_posting_footer_long.xml
  res/layout/list_item_post.xml
  res/layout/widget_common_captcha_block.xml
  res/values/attrs.xml
  res/values/colors.xml
  res/values/dimens.xml
  res/values/styles.xml
  src/com/mishiranu/dashchan/C.java
  src/com/mishiranu/dashchan/content/Preferences.java
  src/com/mishiranu/dashchan/content/storage/DraftsStorage.java
  src/com/mishiranu/dashchan/ui/CaptchaForm.java
  src/com/mishiranu/dashchan/ui/CaptchaOptionsDialog.java
  src/com/mishiranu/dashchan/ui/ForegroundManager.java
  src/com/mishiranu/dashchan/ui/navigator/manager/ViewUnit.java
  src/com/mishiranu/dashchan/ui/navigator/page/PostsPage.java
  src/com/mishiranu/dashchan/ui/posting/PostingFragment.java
  src/com/mishiranu/dashchan/ui/preference/InterfaceFragment.java
  src/com/mishiranu/dashchan/util/CaptchaUtils.java
  src/com/mishiranu/dashchan/widget/EdgeEffectHandler.java
  src/com/mishiranu/dashchan/widget/ImportantPostsMarksFastScrollBarDecoration.java
  src/com/mishiranu/dashchan/widget/PaddedRecyclerView.java
  src/com/mishiranu/dashchan/widget/PostBorderView.java
Labels: bug, enhancement

#96 Add option to enable / disable posts borders to interface preferences
  lang/values-ru/strings.xml
  lang/values/strings.xml
  src/com/mishiranu/dashchan/content/Preferences.java
  src/com/mishiranu/dashchan/ui/navigator/manager/ViewUnit.java
  src/com/mishiranu/dashchan/ui/preference/InterfaceFragment.java
Labels: enhancement

#97 Fix crash when updating important posts scroll bar data and a thread has deleted posts
  src/com/mishiranu/dashchan/ui/navigator/page/PostsPage.java
Labels: bug

#100 Ability to remove space after quote
  lang/values-ru/strings.xml
  lang/values/strings.xml
  src/com/mishiranu/dashchan/content/Preferences.java
  src/com/mishiranu/dashchan/ui/posting/PostingFragment.java
  src/com/mishiranu/dashchan/ui/preference/InterfaceFragment.java
Labels: enhancement

#98 Attachment features
  lang/values-ru/strings.xml
  lang/values/strings.xml
  res/layout/dialog_filename.xml
  src/chan/util/StringUtils.java
  src/com/mishiranu/dashchan/content/Preferences.java
  src/com/mishiranu/dashchan/content/storage/DraftsStorage.java
  src/com/mishiranu/dashchan/ui/posting/AttachmentHolder.java
  src/com/mishiranu/dashchan/ui/posting/PostingFragment.java
  src/com/mishiranu/dashchan/ui/posting/dialog/AttachmentOptionsDialog.java
  src/com/mishiranu/dashchan/ui/preference/MediaFragment.java
  src/com/mishiranu/dashchan/widget/MaterialButton.java
Labels: enhancement

#102 Increase clickable toast message max lines to 3
  src/com/mishiranu/dashchan/widget/ClickableToast.java
Labels: enhancement, questionable

#106 Fix keyboard not showing in AttachmentOptionsDialog
  src/com/mishiranu/dashchan/ui/posting/dialog/AttachmentOptionsDialog.java
Labels: bug

#104 Fix possible crash when cancel all downloads
  src/com/mishiranu/dashchan/content/service/DownloadService.java
Labels: bug

#103 Add ability to paste rich content to the post form
  res/layout/activity_posting.xml
  src/com/mishiranu/dashchan/ui/posting/PostingFragment.java
  src/com/mishiranu/dashchan/widget/UriPasteEditText.java
Labels: enhancement

#105 Add ability to copy images to clipboard
  lang/values-ru/strings.xml
  lang/values/strings.xml
  src/com/mishiranu/dashchan/C.java
  src/com/mishiranu/dashchan/content/CacheManager.java
  src/com/mishiranu/dashchan/content/FileProvider.java
  src/com/mishiranu/dashchan/content/FileUriClipboard.java
  src/com/mishiranu/dashchan/ui/gallery/PagerUnit.java
Labels: enhancement

#108 Show toast message after pasting rich content from the keyboard
  lang/values-ru/strings.xml
  lang/values/strings.xml
  src/com/mishiranu/dashchan/widget/UriPasteEditText.java
Labels: enhancement

#109 Trixiether/enhancement/readme update
  README.md
  metadata/en-US/images/phoneScreenshots/10.png
  metadata/en-US/images/phoneScreenshots/11.png
  metadata/en-US/images/phoneScreenshots/9.png
Labels: enhancement
