Repository TrixiEther/DashchanFork, pull requests merged in 2023-08, with the labels that each got.

#110 Destroy WebView after WebViewDialog's view is destroyed
  src/com/mishiranu/dashchan/ui/WebViewDialog.java
Labels: bug

#111 TrixiEther | Attachment features was broken
  src/com/mishiranu/dashchan/ui/posting/dialog/AttachmentOptionsDialog.java
Labels: bug

#112 TrixiEther | Release 1.6.2
  build.gradle
  metadata/en-US/changelogs/1053.txt
  metadata/ru/changelogs/1053.txt
  metadata/versions.json
Labels: enhancement

#113 3.1.4-experimental-1.6.2
  README.md
  build.gradle
  lang/values-ru/strings.xml
  lang/values/strings.xml
  metadata/en-US/changelogs/1053.txt
  metadata/en-US/images/phoneScreenshots/10.png
  metadata/en-US/images/phoneScreenshots/11.png
  metadata/en-US/images/phoneScreenshots/9.png
  metadata/ru/changelogs/1053.txt
  metadata/versions.json
  res/layout/activity_posting.xml
  res/layout/dialog_filename.xml
  src/chan/util/StringUtils.java
  src/com/mishiranu/dashchan/C.java
  src/com/mishiranu/dashchan/content/CacheManager.java
  src/com/mishiranu/dashchan/content/FileProvider.java
  src/com/mishiranu/dashchan/content/FileUriClipboard.java
  src/com/mishiranu/dashchan/content/Preferences.java
  src/com/mishiranu/dashchan/content/model/PostItem.java
  src/com/mishiranu/dashchan/content/service/DownloadService.java
  src/com/mishiranu/dashchan/content/storage/DraftsStorage.java
  src/com/mishiranu/dashchan/ui/WebViewDialog.java
  src/com/mishiranu/dashchan/ui/gallery/GalleryOverlay.java
  src/com/mishiranu/dashchan/ui/gallery/PagerUnit.java
  src/com/mishiranu/dashchan/ui/navigator/adapter/PostsAdapter.java
  src/com/mishiranu/dashchan/ui/navigator/manager/ViewUnit.java
  src/com/mishiranu/dashchan/ui/navigator/page/PostsPage.java
  src/com/mishiranu/dashchan/ui/posting/AttachmentHolder.java
  src/com/mishiranu/dashchan/ui/posting/PostingFragment.java
  src/com/mishiranu/dashchan/ui/posting/dialog/AttachmentOptionsDialog.java
  src/com/mishiranu/dashchan/ui/preference/InterfaceFragment.java
  src/com/mishiranu/dashchan/ui/preference/MediaFragment.java
  src/com/mishiranu/dashchan/widget/ClickableToast.java
  src/com/mishiranu/dashchan/widget/MaterialButton.java
  src/com/mishiranu/dashchan/widget/UriPasteEditText.java
Labels: enhancement

#115 TrixiEther | Readme 1.6.2
  README.md
  metadata/en-US/images/phoneScreenshots/11.png
  metadata/en-US/images/phoneScreenshots/12.png
  metadata/en-US/images/phoneScreenshots/13.png
Labels: documentation
