Repository TrixiEther/DashchanFork, pull requests merged in 2023-06, with the labels that each got.

#86 Do not show marks on scroll bar for hidden posts
  src/com/mishiranu/dashchan/ui/navigator/page/PostsPage.java
Labels: enhancement, questionable

#88 Fix gallery crash after process death
  src/com/mishiranu/dashchan/ui/gallery/GalleryOverlay.java
Labels: bug, enhancement

#85 Complete hiding of posts
  lang/values-ru/strings.xml
  lang/values/strings.xml
  src/com/mishiranu/dashchan/content/Preferences.java
  src/com/mishiranu/dashchan/content/model/PostItem.java
  src/com/mishiranu/dashchan/ui/navigator/adapter/PostsAdapter.java
  src/com/mishiranu/dashchan/ui/navigator/page/PostsPage.java
  src/com/mishiranu/dashchan/ui/preference/InterfaceFragment.java
Labels: bug, enhancement

#89 Fix themes and updates urls
  build.gradle
Labels: bug, questionable
