Repository TrixiEther/DashchanFork, pull requests merged in 2023-02, with the labels that each got.

#38 Add themed app icon support
  lang/drawable/ic_launcher_monochrome.xml
  res/mipmap-anydpi-v26/ic_launcher.xml
Labels: enhancement

#37 Fix crash when set text appearance if api < 23
  src/com/mishiranu/dashchan/ui/navigator/manager/ViewUnit.java
Labels: invalid

#40 Improve Cloudflare detection
  src/com/mishiranu/dashchan/content/net/firewall/CloudFlareResolver.java
Labels: enhancement

#35 TrixiEther | Enhancement | iichan https support
  AndroidManifest.xml
  res/raw/iichan_hk_chain.pem
  res/xml/network_config.xml
Labels: enhancement

#41 TrixiEther | Bug | Fix display date
  res/layout/list_item_post.xml
Labels: bug
